import { useWorkflowStore } from '@/domains/workflow/lib/store';
import { useShallow } from 'zustand/react/shallow';

export function useWorkflowPageStore() {
  return useWorkflowStore(
    useShallow((state) => ({
      documents: state.documents,
      activeDocumentId: state.activeDocumentId,
      workflowId: state.workflowId,
      workflowName: state.workflowName,
      workflowList: state.workflowList,
      isHydratingWorkflow: state.isHydratingWorkflow,
      isSavingWorkflow: state.isSavingWorkflow,
      hasUnsavedChanges: state.hasUnsavedChanges,
      lastSavedAt: state.lastSavedAt,
      nodes: state.nodes,
      edges: state.edges,
      selectedNodeId: state.selectedNodeId,
      isExecuting: state.isExecuting,
      executionProgress: state.executionProgress,
      executionMessage: state.executionMessage,
      currentRunId: state.currentRunId,
      executingNodeId: state.executingNodeId,
      lastExecutionStatus: state.lastExecutionStatus,
      lastExecutionTime: state.lastExecutionTime,
      lastExecutionError: state.lastExecutionError,
      lastExecutionSummary: state.lastExecutionSummary,
      snapToGridEnabled: state.snapToGridEnabled,
      setWorkflowName: state.setWorkflowName,
      addNode: state.addNode,
      autoArrangeWorkflow: state.autoArrangeWorkflow,
      applyEditorSnapshot: state.applyEditorSnapshot,
      cancelWorkflowExecution: state.cancelWorkflowExecution,
      createNodeGroup: state.createNodeGroup,
      deleteCurrentWorkflow: state.deleteCurrentWorkflow,
      deleteCurrentWorkflowDetailed: state.deleteCurrentWorkflowDetailed,
      duplicateCurrentWorkflow: state.duplicateCurrentWorkflow,
      duplicateCurrentWorkflowDetailed: state.duplicateCurrentWorkflowDetailed,
      executeWorkflow: state.executeWorkflow,
      executeWorkflowToNode: state.executeWorkflowToNode,
      exportCurrentWorkflow: state.exportCurrentWorkflow,
      importWorkflowData: state.importWorkflowData,
      importWorkflowDataWithMode: state.importWorkflowDataWithMode,
      loadWorkflow: state.loadWorkflow,
      loadWorkflowDetailed: state.loadWorkflowDetailed,
      newWorkflow: state.newWorkflow,
      persistLocalDraft: state.persistLocalDraft,
      saveWorkflow: state.saveWorkflow,
      saveWorkflowDetailed: state.saveWorkflowDetailed,
      setSnapToGridEnabled: state.setSnapToGridEnabled,
      setActiveWorkflowDocument: state.setActiveWorkflowDocument,
      closeWorkflowDocument: state.closeWorkflowDocument,
    })),
  );
}

export function useWorkflowCanvasStore() {
  return useWorkflowStore(
    useShallow((state) => ({
      nodes: state.nodes,
      edges: state.edges,
      isExecuting: state.isExecuting,
      snapToGridEnabled: state.snapToGridEnabled,
      addNode: state.addNode,
      addEdge: state.addEdge,
      executeWorkflowToNode: state.executeWorkflowToNode,
      autoArrangeWorkflow: state.autoArrangeWorkflow,
      createNodeGroup: state.createNodeGroup,
      onEdgesChange: state.onEdgesChange,
      onNodesChange: state.onNodesChange,
      releaseNodesFromGroup: state.releaseNodesFromGroup,
      detachNodeFromChain: state.detachNodeFromChain,
      insertNodeOnEdge: state.insertNodeOnEdge,
      removeEdge: state.removeEdge,
      removeNode: state.removeNode,
      removeNodes: state.removeNodes,
      resetNodeSize: state.resetNodeSize,
      selectNode: state.selectNode,
      toggleGroupCollapsed: state.toggleGroupCollapsed,
      toggleNodesLocked: state.toggleNodesLocked,
      toggleNodesDisabled: state.toggleNodesDisabled,
      ungroupNodes: state.ungroupNodes,
      updateGroupPort: state.updateGroupPort,
      updateNodeData: state.updateNodeData,
    })),
  );
}
