export {
  STORAGE_PATHS,
  ensureStorageDirectories,
  ensureDir,
  ensureJsonFile,
  readJsonFile,
  writeJsonFile,
  safeResolveWithin,
  APP_CONFIG_DIR_NAME,
  BACKEND_ROOT,
  PROJECT_ROOT,
  getDefaultConfigRoot,
  getStorageRoot,
  clearStoredStorageRootOverride,
  getBootstrapConfigPath,
  getEffectiveStorageRootInfo,
  getStoredStorageRootOverride,
  writeStoredStorageRootOverride,
  LEGACY_PATHS,
  migrateLegacyStorageIfNeeded,
  SCOPED_STORAGE_LAYOUT_VERSION,
  createStorageNamespace,
  ensureScopedStorageDirectories,
  getScopedStoragePaths,
  isDefaultStorageScope,
  isResourceVisibleForScope,
} from './index.ts';
